tap "heroku/brew"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-drivers"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "homebrew/services"
tap "thoughtbot/formulae"

brew "autoconf"
brew "automake"
brew "coreutils"
brew "curl"
brew "gettext"
brew "gh"
brew "git"
brew "gnupg"
brew "heroku/brew/heroku"
brew "hivemind"
brew "htop"
brew "imagemagick"
brew "jq"
brew "mas"
brew "node"
brew "npm"
brew "openssl"
brew "overmind"
brew "python"
brew "tree"
brew "unzip"
brew "watch"
brew "wget"
brew "wxwidgets"
brew "yarn"
brew "youtube-dl"
brew "yq"
brew "zsh-completions"
brew "zsh-syntax-highlighting"

cask "alfred"
cask "chromedriver"
cask "discord"
cask "dropbox"
cask "docker"
cask "fantastical"
cask "figma"
cask "firefox"
cask "font-fira-code"
cask "font-fira-mono"
cask "google-chrome"
cask "google-drive"
cask "insomnia"
cask "iterm2"
cask "obsidian"
cask "oracle-jdk"
cask "postman"
cask "slack"
cask "todoist"
cask "visual-studio-code"
cask "vlc"
cask "zoom"

mas "Bear", id: 1091189122
mas "Goodnotes", id: 1444383602
mas "Magnet", id: 441258766
mas "MonoSnap", id: 540348655
mas "Trello", id: 1278508951
